name: Validate renovate config

on:
  pull_request:
  push:
    branches: main

env:
  CACHE_DIR: /tmp/.npm-cache

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-node
      - name: Validate renovate config
        run: |
          for file in *.json*
          do
            if [[ "$file" == "package.json" || "$file" == "renovate.json" ]]; then
              echo "Skip: $file"
              continue
            fi
            echo "Validate: $file"
            RENOVATE_CONFIG_FILE=${file} npx --package renovate -c 'renovate-config-validator'
          done
